version: '3'
services:
  hello-world-demo:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: hello-world-demo
    container_name: hello-world-demo
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "start_with_request=yes output_dir=/var/www/html/.xdebug profiler_enable_trigger=1 client_host=host.docker.internal client_port=9003"
    ports:
      - '80:80'
    volumes:
        - './src:/var/www/html'